### ISSUE TITLE
General usage problems

### ISSUE THREAD

**Issue by maljes** [catalyst/assignsubmission-maharaws#10]
First of all, I like the functionality of the plugin and I think it is very useful, but I have a few questions about how to use it.

As I understand the plugin, the Mahara connection must be reconfigured for each submission. This means every teacher who wants to setup a submission with portfolios would have to ask the administrator for the OAuth credentials. Do I need to register a new external application in Mahara for each submission?

If so, I consider this procedure to be highly complicated.

To me, it should be possible to configure the plugin, like an external tool, in the backend with the credentials, so that the teacher only has to check the box for "Mahara".

Another problem during my test was that we had configured the login to Mahara via LDAP. If the user logs into Mahara first, the user account is created normally. However, if the user logs in via the plugin first, the user name is prefixed with the type. If the user then logs in to Mahara via LDAP, two different accounts are created for one user, because no matching username could be found.

I hope my problems are understandable so far.

**Comment by maljes** [comment]
#5 would solve at least on of my problems.

**Comment by dmitriim** [comment]
Looks like it was merged. And the issue can be closed.
