### ISSUE TITLE
Username / remote username is incorrect and receives 'email:' as prefix

### ISSUE THREAD

**Issue by anitsirk** [catalyst/assignsubmission-maharaws#13]
When an account is created solely through the plugin, i.e. account didn't exist on Mahara, and a regular LTI call via the 'External tool' hadn't already been made, then the username / remote username comes across incorrectly as 'email:emailaddress@theaccount.holder'.

This causes problems, in particular for external authentication methods.

To test:

1. As Mahara site admin: Create the LTI details on Mahara.
2. As Moodle site admin: Set up the plugin and configure it with the LTI details from Mahara.
2. Create an assignment that allows the submission of a portfolio.
3. Log in as student who does not yet have an account on Mahara.
4. Click in the assignment to add a new portfolio in Mahara as they wouldn't already have one. You are taken to Mahara and an account is created.
5. As Mahara site admin: Check username / remote username. It has 'email:' before the email address, which is not correct. It should either be the regular Moodle username or email address as username and the remote username typically has the Moodle user ID or a special, longer identifier.

In contrast:

1. As Moodle site admin: Set up Mahara as external tool (either on site admin or in the course context)
2. Log in to Mahara using these details.
3. as Mahara site admin check the account: Username is the Moodle username.

**Comment by LoveBug** [comment]
I have created a merge request that addresses this issue.
It does change default behaviour, and could cause issues for existing installs so I have made this a configuration option.

**Comment by dmitriim** [comment]
Fixed as part of https://github.com/catalyst/assignsubmission-maharaws/pull/16
